efiBootloaderId: "debian"
installEFIFallback: false
grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
grubProbe: "grub-probe"
efiVarsPath: "/sys/firmware/efi/efivars"
canBeNextBootEntry: true
