defaultGroups:
  - cdrom
  - floppy
  - sudo
  - audio
  - dip
  - video
  - plugdev
  - netdev
  - lpadmin
  - scanner
  - bluetooth

autologinGroup: autologin
doAutologin: true
sudoersGroup: sudo
setRootPassword: false
doReusePassword: false
passwordRequirements:
  minLength: 6
  maxLength: -1
  libpwquality:
    - minlen=6
userShell: /bin/bash
